name: Status Check

on:
  deployment_status
jobs:
  
  spectacles: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo url : {{ github.event.deployment_status.target_url }}
          echo status : {{ github.event.deployment_status.state }}

