name: Deploy Development

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo "deployment succeeded!"
