name: Deploy Development

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: Development
    env:
      TEST_VAR: ${{ vars.TEST_VAR }}
    steps:
      - name: deploy
        run: |
          echo "deployment failed! TEST_VAR=${TEST_VAR}"
          return 1
