name: Deploy Production

on:
  push:
    branches:
      - production

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: Production
    env:
      TEST_VAR: ${{ vars.TEST_VAR }}
    steps:
      - name: deploy
        run: |
          echo "deployment succeeded! TEST_VAR=${TEST_VAR}"
