name: Deploy Development

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: Development
    env:
      TEST_VAR: ${{ vars.TEST_VAR }}
    steps:
      - name: deploy
        id: deploy
        run: |
          echo "deployment completed! TEST_VAR=${TEST_VAR}"
        # continue-on-error: true
      - name: Check on success
        if: steps.deploy.status == 'success'
        run: |
          echo "deployment success status  ${{ steps.deploy.status  }}"
          exit 0
      - name: Check on failures
        if: steps.deploy.status == 'failure'
        run: |
          echo "deployment failed status  ${{ steps.deploy.status  }}"
          exit 1

