name: Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: Staging
    env:
      TEST_VAR: ${{ vars.TEST_VAR }}
    steps:
      - name: deploy
        run: |
          echo "deployment succeeded! TEST_VAR=${TEST_VAR}"
