name: Deploy Development

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
      - name: deploy
        run: |
          echo "deployment succeeded! TEST_VAR=${TEST_VAR}"
